#!/bin/sh

case $1 in
        a*|add*)
                echo "$2" >> ~/todo
                ;;
        s*|show*)
                if [ "$2" = all -o -z "$2" ]; then
                        nl ~/todo
                else
                        echo $(sed -n "$2"p ~/todo)
                fi
                ;;
        d*|del*)
                sed -i".old" "$2"d ~/todo
                rm ~/todo.old
                ;;
        *)
                echo "Invalid command"
                exit -1
                ;;
esac
